# Generated by Django 2.1.7 on 2019-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_auto_20190321_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(max_length=12, primary_key=True, serialize=False, unique=True,
                                      verbose_name='Aadhaar card number'),
        ),
    ]
