# Generated by Django 2.1.5 on 2019-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190309_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractorinfo',
            name='Tractor_Name',
            field=models.CharField(default='Unkown', max_length=150),
        ),
    ]
