# Generated by Django 2.1.5 on 2019-03-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_tractorinfo_tractor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorinfo',
            name='Image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
