# Generated by Django 2.1.5 on 2019-03-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190309_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(choices=[('MH', 'Maharashtra')], default='MH', max_length=2)),
                ('city', models.CharField(choices=[('TH', 'Thane')], default='TH', max_length=2)),
                ('address', models.TextField()),
            ],
        ),
    ]
