# Generated by Django 2.1.5 on 2019-03-11 07:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190311_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerinfo',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
