# Generated by Django 2.1.5 on 2019-03-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190311_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='TractorInfoForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(choices=[('1', 'John Deere'), ('2', 'Tafe'), ('3', 'Escorts'), ('4', 'Swaraj'), ('5', 'Mahindra'), ('6', 'Sonalika'), ('7', 'Trakstar'), ('8', 'Kubota')], default='1', max_length=30)),
                ('model_name', models.CharField(max_length=30)),
                ('implement', models.CharField(choices=[('1', 'Baler'), ('2', 'Combine Harvester'), ('3', 'Cultivator'), ('4', 'Disc Harrow'), ('5', 'Disc Plough'), ('6', 'Hole Digger'), ('7', 'Hydraulic reversible plough '), ('8', 'Mould Board Plough'), ('9', 'Potato Harvester'), ('10', 'Power Harrow'), ('11', 'Power Tiller'), ('12', 'Rice Transplanter'), ('13', 'Rotary Tiller'), ('14', 'Rotavator'), ('15', 'Row Potato Planter'), ('16', 'Seed Drill'), ('17', 'Sprayer'), ('18', 'Straw Reaper'), ('19', 'Sugarcane Harvester'), ('20', 'Thresher')], default='1', max_length=2)),
                ('rent_choice', models.CharField(choices=[('ACER', 'PER ACER'), ('HOUR', 'PER HOUR')], default='HOUR', max_length=10)),
                ('working_radius', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name='city',
            field=models.CharField(choices=[('TH', 'Thane'), ('NA', 'Nashik'), ('DH', 'Dhule'), ('AK', 'Akola'), ('CH', 'Chandrapu'), ('LA', 'Latur'), ('PA', 'Parbhani'), ('SO', 'Solapur'), ('YA', 'Yavatmal')], default='TH', max_length=2),
        ),
    ]
