# Generated by Django 2.1.5 on 2019-03-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorinfo',
            name='Drive',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tractorinfo',
            name='Hp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tractorinfo',
            name='RentPerHour',
            field=models.IntegerField(),
        ),
    ]
