# Generated by Django 2.1.5 on 2019-03-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_ownerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
