# Generated by Django 2.1.5 on 2019-03-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20190313_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentform',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='rentform',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
